package nop
package driver

import frontend.lexer.Span
import frontend.lexer.WithSpan

type Note = WithSpan[String]

/** Diagnostic generated by frontend. Used for printing in driver. */
case class Diagnostic(msg: String, span: Span, notes: Seq[Note] = Nil)
