[package]
name = "driver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
frontend = { path = "../frontend" }

[[bin]]
name = "nop"
path = "src/main.rs"
